version: "3.9"

services:

  db:
    image: keinos/sqlite3
    container_name: sqlite-db
    stdin_open: true
    tty: true

  app:
    build: .
    container_name: python-app
    depends_on:
      - db